//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRIZBD_Lab4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Awards
    {
        public int award_id { get; set; }
        public int graduate_id { get; set; }
        public string award_name { get; set; }
        public int award_year { get; set; }
    
        public virtual Graduates Graduates { get; set; }
    }
}
