//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRIZBD_Lab4
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiplomaWorks
    {
        public int diploma_id { get; set; }
        public int graduate_id { get; set; }
        public int advisor_id { get; set; }
        public string title { get; set; }
        public int year { get; set; }
    
        public virtual Graduates Graduates { get; set; }
        public virtual ScientificAdvisors ScientificAdvisors { get; set; }
    }
}
