//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRIZBD_Lab4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UniversityDBEntities : DbContext
    {
        private static UniversityDBEntities _context;
        public UniversityDBEntities()
            : base("name=UniversityDBEntities")
        {
        }

        public static UniversityDBEntities GetContext()
        {
            if(_context == null)
                _context = new UniversityDBEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Awards> Awards { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<DiplomaWorks> DiplomaWorks { get; set; }
        public virtual DbSet<Graduates> Graduates { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<ScientificAdvisors> ScientificAdvisors { get; set; }
        public virtual DbSet<Skills> Skills { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
