//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRIZBD_Lab4
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScientificAdvisors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScientificAdvisors()
        {
            this.DiplomaWorks = new HashSet<DiplomaWorks>();
        }
    
        public int advisor_id { get; set; }
        public int user_id { get; set; }
        public int department_id { get; set; }
    
        public virtual Departments Departments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiplomaWorks> DiplomaWorks { get; set; }
        public virtual Users Users { get; set; }
    }
}
